# Task Configuration
title: 'Angular Refactoring Skill'
position: 5
category: 'Skills'
preparation: false
estimated_time_in_minutes: 25
always_unlocked: false
git_tag_completed: solution--skill-se-blue
